# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: web-goat-pool

steps:

- task: Maven@4
  displayName: Maven Install
  inputs:
    mavenPomFile: 'WebGoatProject/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'nxiq-WebGoat'
    organizationId: 'f2393bc70ea94449b91fbc3956ed8964'
    applicationId: 'wgj'
    stage: 'Build'
    scanPipelineWorkspace: true
   
    

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

